/** Position Applied For — workForce table multipleSelects (Airtable). */
export const CAREER_POSITIONS = [
  "Deep Cleaner",
  "Pressure Washer",
  "Roof & Gutter Cleaner",
  "Handyman",
  "Carpenter",
  "Plumber",
  "Electrical Repairer",
  "Flooring Fixer",
  "Washing Machine Repairer",
  "Smart Home Setup",
  "EV Charger Installer",
  "AC Servicing",
  "Painter",
  "Wallpaper Fixer",
  "Drywall Repairer",
  "Tile Worker",
  "Window Repairer",
  "Floor Repairer",
  "Lawn Care",
  "Tree Cutter",
  "Garden Care",
  "Irrigation Installer",
  "Fence Repairer",
  "Outdoor Lighting Installer",
  "Mover",
  "Airbnb Maintenance",
  "Packing",
  "Home Concierge",
  "Cleaning Planner",
  "Maintenance Planner",
  "Carpentry",
] as const;

/** Preferred Working Area — workForce multipleSelects (Kathmandu + Other). */
export const PREFERRED_WORKING_AREAS = [
  "Asan",
  "Balaju",
  "Baluwatar",
  "Baneshwor",
  "Basundhara",
  "Bhaisepati",
  "Bhaktapur",
  "Bouddha",
  "Budhanilkantha",
  "Chabahil",
  "Changunarayan",
  "Chundevi",
  "Dhapasi",
  "Durbar Marg",
  "Ekantakuna",
  "Gaushala",
  "Godawari",
  "Gongabu",
  "Gwarko",
  "Gyaneshwor",
  "Harisiddhi",
  "Imadol",
  "Jawalakhel",
  "Jorpati",
  "Kalanki",
  "Kalimati",
  "Kamalbinayak",
  "Kamalpokhari",
  "Kirtipur",
  "Koteshwor",
  "Khusibu",
  "Kupondole",
  "Lagankhel",
  "Lazimpat",
  "Machhapokhari",
  "Maharajgunj",
  "Mangal Bazar",
  "Naikap",
  "Nayabazar",
  "New Baneshwor",
  "New Road",
  "Patan",
  "Pulchowk",
  "Putalisadak",
  "Ranibari",
  "Samakhusi",
  "Sanepa",
  "Satdobato",
  "Sitapaila",
  "Sinamangal",
  "Sukedhara",
  "Sundhara",
  "Suryabinayak",
  "Swayambhu",
  "Teku",
  "Thamel",
  "Thaiba",
  "Thankot",
  "Thimi",
  "Tokha",
  "Tripureshwor",
  "Other",
] as const;

export const YEARS_OF_EXPERIENCE_OPTIONS = [
  "Less than 1 year",
  "1 year",
  "2 years",
  "3 years",
  "4 years",
  "5 years",
  "6–10 years",
  "11–15 years",
  "16–20 years",
  "More than 20 years",
] as const;

export const MAX_CAREER_FILE_MB = 5;
